import "./globals.css";
import { UserProvider } from "@/utils/userContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="en">
        <head>
          <meta charSet="UTF-8" />
        </head>
        <body>
          {children}
        </body>
      </html>
    </UserProvider>
  );
}
